### ISSUE TITLE
wandb question

### ISSUE THREAD

**Issue by Caomingming666** [sa-and/CORE#1]
wandb: Network error (SSLError), entering retry loop.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (SSLError), entering retry loop.
I should how to solve？Please ，┭┮﹏┭┮

**Comment by Caomingming666** [comment]
D:\PythonProject\CasualityRL\CORE-main\Scripts\python.exe D:\PythonProject\CORE-main\train.py 
wandb: Tracking run with wandb version 0.14.2
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Traceback (most recent call last):
  File "D:\PythonProject\CORE-main\train.py", line 162, in <module>
    train(args)
  File "D:\PythonProject\CORE-main\train.py", line 89, in train
    env = SCMEnvironmentReservoir(n_vars, DiscreteAgentInterventionStructure, FixedLengthStructEpisode,
  File "D:\PythonProject\CORE-main\envs\environments.py", line 221, in __init__
    self.current_env = self.get_next_env(new_env=True)
  File "D:\PythonProject\CORE-main\envs\environments.py", line 272, in get_next_env
    scm = self.gen.create_scm_from_graph(graph, possible_functions=[k for k in self.possible_functions])
  File "D:\PythonProject\CORE-main\envs\generation\scm_gen.py", line 174, in create_scm_from_graph
    scm.add_endogenous_var(n, 0.0, self.all_functions[current_function](parents), {p: p for p in parents})
KeyError: 'xor'
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync D:\PythonProject\CORE-main\wandb\offline-run-20241220_172800-ibr5w6xb
wandb: Find logs at: .\wandb\offline-run-20241220_172800-ibr5w6xb\logs

进程已结束，退出代码为 1

I select offline ，but appear this question。
